#!/usr/bin/env bash

# Git, rest in .gitconfig
alias g='git'

# ls
alias ls='ls --color=auto'
alias l='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias lc='ls -CF'

# cp
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
